language: python

before_install:
  - pip install codecov
  - sudo apt install python3
install:
  - pip install -r requirements.txt
after_success:
  - codecov --file coverage/lcov.info --disable search